In [31]:
# Import necessary Libraries
import pandas as pd
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# open csv file and load the data into pandas dataframe
appl_df = pd.read_csv('../data/raw/loan.csv', low_memory=False)
appl_df.info()

/Users/ashish/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (19,47,55,112,123,124,125,128,129,130,133,139,140,141) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2260668 entries, 0 to 2260667
Columns: 145 entries, id to settlement_term
dtypes: float64(105), int64(4), object(36)
memory usage: 2.4+ GB

In [18]:
appl_df.dtypes

id                                            float64
member_id                                     float64
loan_amnt                                       int64
funded_amnt                                     int64
funded_amnt_inv                               float64
term                                           object
int_rate                                      float64
installment                                   float64
grade                                          object
sub_grade                                      object
emp_title                                      object
emp_length                                     object
home_ownership                                 object
annual_inc                                    float64
verification_status                            object
issue_d                                        object
loan_status                                    object
pymnt_plan                                     object
url                                           float64
desc                                           object
purpose                                        object
title                                          object
zip_code                                       object
addr_state                                     object
dti                                           float64
delinq_2yrs                                   float64
earliest_cr_line                               object
inq_last_6mths                                float64
mths_since_last_delinq                        float64
mths_since_last_record                        float64
open_acc                                      float64
pub_rec                                       float64
revol_bal                                       int64
revol_util                                    float64
total_acc                                     float64
initial_list_status                            object
out_prncp                                     float64
out_prncp_inv                                 float64
total_pymnt                                   float64
total_pymnt_inv                               float64
total_rec_prncp                               float64
total_rec_int                                 float64
total_rec_late_fee                            float64
recoveries                                    float64
collection_recovery_fee                       float64
last_pymnt_d                                   object
last_pymnt_amnt                               float64
next_pymnt_d                                   object
last_credit_pull_d                             object
collections_12_mths_ex_med                    float64
mths_since_last_major_derog                   float64
policy_code                                     int64
application_type                               object
annual_inc_joint                              float64
dti_joint                                     float64
verification_status_joint                      object
acc_now_delinq                                float64
tot_coll_amt                                  float64
tot_cur_bal                                   float64
open_acc_6m                                   float64
open_act_il                                   float64
open_il_12m                                   float64
open_il_24m                                   float64
mths_since_rcnt_il                            float64
total_bal_il                                  float64
il_util                                       float64
open_rv_12m                                   float64
open_rv_24m                                   float64
max_bal_bc                                    float64
all_util                                      float64
total_rev_hi_lim                              float64
inq_fi                                        float64
total_cu_tl                                   float64
inq_last_12m                                  float64
acc_open_past_24mths                          float64
avg_cur_bal                                   float64
bc_open_to_buy                                float64
bc_util                                       float64
chargeoff_within_12_mths                      float64
delinq_amnt                                   float64
mo_sin_old_il_acct                            float64
mo_sin_old_rev_tl_op                          float64
mo_sin_rcnt_rev_tl_op                         float64
mo_sin_rcnt_tl                                float64
mort_acc                                      float64
mths_since_recent_bc                          float64
mths_since_recent_bc_dlq                      float64
mths_since_recent_inq                         float64
mths_since_recent_revol_delinq                float64
num_accts_ever_120_pd                         float64
num_actv_bc_tl                                float64
num_actv_rev_tl                               float64
num_bc_sats                                   float64
num_bc_tl                                     float64
num_il_tl                                     float64
num_op_rev_tl                                 float64
num_rev_accts                                 float64
num_rev_tl_bal_gt_0                           float64
num_sats                                      float64
num_tl_120dpd_2m                              float64
num_tl_30dpd                                  float64
num_tl_90g_dpd_24m                            float64
num_tl_op_past_12m                            float64
pct_tl_nvr_dlq                                float64
percent_bc_gt_75                              float64
pub_rec_bankruptcies                          float64
tax_liens                                     float64
tot_hi_cred_lim                               float64
total_bal_ex_mort                             float64
total_bc_limit                                float64
total_il_high_credit_limit                    float64
revol_bal_joint                               float64
sec_app_earliest_cr_line                       object
sec_app_inq_last_6mths                        float64
sec_app_mort_acc                              float64
sec_app_open_acc                              float64
sec_app_revol_util                            float64
sec_app_open_act_il                           float64
sec_app_num_rev_accts                         float64
sec_app_chargeoff_within_12_mths              float64
sec_app_collections_12_mths_ex_med            float64
sec_app_mths_since_last_major_derog           float64
hardship_flag                                  object
hardship_type                                  object
hardship_reason                                object
hardship_status                                object
deferral_term                                 float64
hardship_amount                               float64
hardship_start_date                            object
hardship_end_date                              object
payment_plan_start_date                        object
hardship_length                               float64
hardship_dpd                                  float64
hardship_loan_status                           object
orig_projected_additional_accrued_interest    float64
hardship_payoff_balance_amount                float64
hardship_last_payment_amount                  float64
disbursement_method                            object
debt_settlement_flag                           object
debt_settlement_flag_date                      object
settlement_status                              object
settlement_date                                object
settlement_amount                             float64
settlement_percentage                         float64
settlement_term                               float64
dtype: object

In [11]:
appl_df.describe()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,url,dti,...,deferral_term,hardship_amount,hardship_length,hardship_dpd,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,settlement_amount,settlement_percentage,settlement_term
count,0.0,0.0,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260664e+06,0.0,2.258957e+06,...,10613.0,10613.000000,10613.0,10613.000000,8426.000000,10613.000000,10613.000000,33056.000000,33056.000000,33056.000000
mean,NaN,NaN,1.504693e+04,1.504166e+04,1.502344e+04,1.309291e+01,4.458076e+02,7.799243e+04,NaN,1.882420e+01,...,3.0,155.006696,3.0,13.686422,454.840802,11628.036442,193.606331,5030.606922,47.775600,13.148596
std,NaN,NaN,9.190245e+03,9.188413e+03,9.192332e+03,4.832114e+00,2.671737e+02,1.126962e+05,NaN,1.418333e+01,...,0.0,129.113137,0.0,9.728138,375.830737,7615.161123,198.694368,3692.027842,7.336379,8.192319
min,NaN,NaN,5.000000e+02,5.000000e+02,0.000000e+00,5.310000e+00,4.930000e+00,0.000000e+00,NaN,-1.000000e+00,...,3.0,0.640000,3.0,0.000000,1.920000,55.730000,0.010000,44.210000,0.200000,0.000000
25%,NaN,NaN,8.000000e+03,8.000000e+03,8.000000e+03,9.490000e+00,2.516500e+02,4.600000e+04,NaN,1.189000e+01,...,3.0,59.370000,3.0,5.000000,174.967500,5628.730000,43.780000,2227.000000,45.000000,6.000000
50%,NaN,NaN,1.290000e+04,1.287500e+04,1.280000e+04,1.262000e+01,3.779900e+02,6.500000e+04,NaN,1.784000e+01,...,3.0,119.040000,3.0,15.000000,352.605000,10044.220000,132.890000,4172.855000,45.000000,14.000000
75%,NaN,NaN,2.000000e+04,2.000000e+04,2.000000e+04,1.599000e+01,5.933200e+02,9.300000e+04,NaN,2.449000e+01,...,3.0,213.260000,3.0,22.000000,622.792500,16114.940000,284.180000,6870.782500,50.000000,18.000000
max,NaN,NaN,4.000000e+04,4.000000e+04,4.000000e+04,3.099000e+01,1.719830e+03,1.100000e+08,NaN,9.990000e+02,...,3.0,943.940000,3.0,37.000000,2680.890000,40306.410000,1407.860000,33601.000000,521.350000,181.000000

In [14]:
appl_df.describe().T

                                                count           mean            std           min         25%            50%            75%           max
id                                                0.0            NaN            NaN           NaN         NaN            NaN            NaN           NaN
member_id                                         0.0            NaN            NaN           NaN         NaN            NaN            NaN           NaN
loan_amnt                                   2260668.0   15046.931228    9190.245488  5.000000e+02   8000.0000   12900.000000   20000.000000  4.000000e+04
funded_amnt                                 2260668.0   15041.664057    9188.413022  5.000000e+02   8000.0000   12875.000000   20000.000000  4.000000e+04
funded_amnt_inv                             2260668.0   15023.437624    9192.331807  0.000000e+00   8000.0000   12800.000000   20000.000000  4.000000e+04
int_rate                                    2260668.0      13.092913       4.832114  5.310000e+00      9.4900      12.620000      15.990000  3.099000e+01
installment                                 2260668.0     445.807646     267.173725  4.930000e+00    251.6500     377.990000     593.320000  1.719830e+03
annual_inc                                  2260664.0   77992.428687  112696.199574  0.000000e+00  46000.0000   65000.000000   93000.000000  1.100000e+08
url                                               0.0            NaN            NaN           NaN         NaN            NaN            NaN           NaN
dti                                         2258957.0      18.824196      14.183329 -1.000000e+00     11.8900      17.840000      24.490000  9.990000e+02
delinq_2yrs                                 2260639.0       0.306879       0.867230  0.000000e+00      0.0000       0.000000       0.000000  5.800000e+01
inq_last_6mths                              2260638.0       0.576835       0.885963  0.000000e+00      0.0000       0.000000       1.000000  3.300000e+01
mths_since_last_delinq                      1102166.0      34.540916      21.900471  0.000000e+00     16.0000      31.000000      50.000000  2.260000e+02
mths_since_last_record                       359156.0      72.312842      26.464094  0.000000e+00     55.0000      74.000000      92.000000  1.290000e+02
open_acc                                    2260639.0      11.612402       5.640861  0.000000e+00      8.0000      11.000000      14.000000  1.010000e+02
pub_rec                                     2260639.0       0.197528       0.570515  0.000000e+00      0.0000       0.000000       0.000000  8.600000e+01
revol_bal                                   2260668.0   16658.458078   22948.305028  0.000000e+00   5950.0000   11324.000000   20246.000000  2.904836e+06
revol_util                                  2258866.0      50.337696      24.713073  0.000000e+00     31.5000      50.300000      69.400000  8.923000e+02
total_acc                                   2260639.0      24.162552      11.987528  1.000000e+00     15.0000      22.000000      31.000000  1.760000e+02
out_prncp                                   2260668.0    4446.292883    7547.611729  0.000000e+00      0.0000       0.000000    6712.632500  4.000000e+04
out_prncp_inv                               2260668.0    4445.294869    7546.656886  0.000000e+00      0.0000       0.000000    6710.320000  4.000000e+04
total_pymnt                                 2260668.0   11824.030498    9889.599027  0.000000e+00   4272.5800    9060.869904   16707.972704  6.329688e+04
total_pymnt_inv                             2260668.0   11805.943515    9884.834668  0.000000e+00   4257.7300    9043.080000   16682.572500  6.329688e+04
total_rec_prncp                             2260668.0    9300.142079    8304.885568  0.000000e+00   2846.1800    6823.385000   13397.500000  4.000000e+04
total_rec_int                               2260668.0    2386.351954    2663.086087  0.000000e+00    693.6100    1485.280000    3052.220000  2.819250e+04
total_rec_late_fee                          2260668.0       1.462469      11.502095 -9.500000e-09      0.0000       0.000000       0.000000  1.427250e+03
recoveries                                  2260668.0     136.073998     725.831678  0.000000e+00      0.0000       0.000000       0.000000  3.985955e+04
collection_recovery_fee                     2260668.0      22.593284     127.111362  0.000000e+00      0.0000       0.000000       0.000000  7.174719e+03
last_pymnt_amnt                             2260668.0    3364.015261    5971.757409  0.000000e+00    308.6400     588.470000    3534.965000  4.219205e+04
collections_12_mths_ex_med                  2260523.0       0.018146       0.150813  0.000000e+00      0.0000       0.000000       0.000000  2.000000e+01
mths_since_last_major_derog                  580775.0      44.164220      21.533121  0.000000e+00     27.0000      44.000000      62.000000  2.260000e+02
policy_code                                 2260668.0       1.000000       0.000000  1.000000e+00      1.0000       1.000000       1.000000  1.000000e+00
annual_inc_joint                             120710.0  123624.636701   74161.346328  5.693510e+03  83400.0000  110000.000000  147995.000000  7.874821e+06
dti_joint                                    120706.0      19.251817       7.822086  0.000000e+00     13.5300      18.840000      24.620000  6.949000e+01
acc_now_delinq                              2260639.0       0.004148       0.069617  0.000000e+00      0.0000       0.000000       0.000000  1.400000e+01
tot_coll_amt                                2190392.0     232.731739    8518.461819  0.000000e+00      0.0000       0.000000       0.000000  9.152545e+06
tot_cur_bal                                 2190392.0  142492.195202  160692.640617  0.000000e+00  29092.0000   79240.000000  213204.000000  9.971659e+06
open_acc_6m                                 1394538.0       0.934420       1.140700  0.000000e+00      0.0000       1.000000       1.000000  1.800000e+01
open_act_il                                 1394539.0       2.779407       3.000784  0.000000e+00      1.0000       2.000000       3.000000  5.700000e+01
open_il_12m                                 1394539.0       0.676431       0.925635  0.000000e+00      0.0000       0.000000       1.000000  2.500000e+01
open_il_24m                                 1394539.0       1.562752       1.578672  0.000000e+00      0.0000       1.000000       2.000000  5.100000e+01
mths_since_rcnt_il                          1350744.0      21.222357      26.049187  0.000000e+00      7.0000      13.000000      24.000000  5.110000e+02
total_bal_il                                1394539.0   35506.645268   44097.455925  0.000000e+00   8695.0000   23127.000000   46095.000000  1.837038e+06
il_util                                     1191818.0      69.140980      23.748386  0.000000e+00     55.0000      72.000000      86.000000  1.000000e+03
open_rv_12m                                 1394539.0       1.290133       1.506827  0.000000e+00      0.0000       1.000000       2.000000  2.800000e+01
open_rv_24m                                 1394539.0       2.749923       2.596911  0.000000e+00      1.0000       2.000000       4.000000  6.000000e+01
max_bal_bc                                  1394539.0    5806.392905    5690.561012  0.000000e+00   2284.0000    4413.000000    7598.000000  1.170668e+06
all_util                                    1394320.0      57.032295      20.904748  0.000000e+00     43.0000      58.000000      72.000000  2.390000e+02
total_rev_hi_lim                            2190392.0   34573.942769   36728.495448  0.000000e+00  14700.0000   25400.000000   43200.000000  9.999999e+06
inq_fi                                      1394539.0       1.012867       1.489456  0.000000e+00      0.0000       1.000000       1.000000  4.800000e+01
total_cu_tl                                 1394538.0       1.477304       2.672991  0.000000e+00      0.0000       0.000000       2.000000  1.110000e+02
inq_last_12m                                1394538.0       2.036667       2.383117  0.000000e+00      0.0000       1.000000       3.000000  6.700000e+01
acc_open_past_24mths                        2210638.0       4.521656       3.164229  0.000000e+00      2.0000       4.000000       6.000000  6.400000e+01
avg_cur_bal                                 2190322.0   13547.797509   16474.075010  0.000000e+00   3080.0000    7335.000000   18783.000000  9.580840e+05
bc_open_to_buy                              2185733.0   11394.262688   16599.534400  0.000000e+00   1722.0000    5442.000000   14187.000000  7.111400e+05
bc_util                                     2184597.0      57.899948      28.583475  0.000000e+00     35.4000      60.200000      83.100000  3.396000e+02
chargeoff_within_12_mths                    2260523.0       0.008464       0.104810  0.000000e+00      0.0000       0.000000       0.000000  1.000000e+01
delinq_amnt                                 2260639.0      12.369828     726.464781  0.000000e+00      0.0000       0.000000       0.000000  2.499250e+05
mo_sin_old_il_acct                          2121597.0     125.737761      53.382175  0.000000e+00     96.0000     130.000000     154.000000  9.990000e+02
mo_sin_old_rev_tl_op                        2190391.0     181.491567      97.118454  1.000000e+00    116.0000     164.000000     232.000000  9.990000e+02
mo_sin_rcnt_rev_tl_op                       2190391.0      14.024089      17.533083  0.000000e+00      4.0000       8.000000      17.000000  5.470000e+02
mo_sin_rcnt_tl                              2190392.0       8.297469       9.208557  0.000000e+00      3.0000       6.000000      11.000000  3.820000e+02
mort_acc                                    2210638.0       1.555382       1.904981  0.000000e+00      0.0000       1.000000       3.000000  9.400000e+01
mths_since_recent_bc                        2187256.0      24.844851      32.319253  0.000000e+00      6.0000      14.000000      30.000000  6.610000e+02
mths_since_recent_bc_dlq                     519701.0      39.303090      22.617689  0.000000e+00     21.0000      37.000000      57.000000  2.020000e+02
mths_since_recent_inq                       1965233.0       7.024194       5.965411  0.000000e+00      2.0000       5.000000      11.000000  2.500000e+01
mths_since_recent_revol_delinq               740359.0      35.782223      22.307239  0.000000e+00     17.0000      33.000000      51.000000  2.020000e+02
num_accts_ever_120_pd                       2190392.0       0.500208       1.350326  0.000000e+00      0.0000       0.000000       0.000000  5.800000e+01
num_actv_bc_tl                              2190392.0       3.676069       2.324646  0.000000e+00      2.0000       3.000000       5.000000  5.000000e+01
num_actv_rev_tl                             2190392.0       5.629468       3.382874  0.000000e+00      3.0000       5.000000       7.000000  7.200000e+01
num_bc_sats                                 2202078.0       4.774183       3.037921  0.000000e+00      3.0000       4.000000       6.000000  7.100000e+01
num_bc_tl                                   2190392.0       7.726402       4.701430  0.000000e+00      4.0000       7.000000      10.000000  8.600000e+01
num_il_tl                                   2190392.0       8.413439       7.359114  0.000000e+00      3.0000       6.000000      11.000000  1.590000e+02
num_op_rev_tl                               2190392.0       8.246523       4.683928  0.000000e+00      5.0000       7.000000      10.000000  9.100000e+01
num_rev_accts                               2190391.0      14.004630       8.038868  0.000000e+00      8.0000      12.000000      18.000000  1.510000e+02
num_rev_tl_bal_gt_0                         2190392.0       5.577951       3.293434  0.000000e+00      3.0000       5.000000       7.000000  6.500000e+01
num_sats                                    2202078.0      11.628130       5.644027  0.000000e+00      8.0000      11.000000      14.000000  1.010000e+02
num_tl_120dpd_2m                            2107011.0       0.000637       0.027106  0.000000e+00      0.0000       0.000000       0.000000  7.000000e+00
num_tl_30dpd                                2190392.0       0.002814       0.056165  0.000000e+00      0.0000       0.000000       0.000000  4.000000e+00
num_tl_90g_dpd_24m                          2190392.0       0.082938       0.493573  0.000000e+00      0.0000       0.000000       0.000000  5.800000e+01
num_tl_op_past_12m                          2190392.0       2.076755       1.830711  0.000000e+00      1.0000       2.000000       3.000000  3.200000e+01
pct_tl_nvr_dlq                              2190237.0      94.114576       9.036140  0.000000e+00     91.3000     100.000000     100.000000  1.000000e+02
percent_bc_gt_75                            2185289.0      42.435127      36.216157  0.000000e+00      0.0000      37.500000      71.400000  1.000000e+02
pub_rec_bankruptcies                        2259303.0       0.128194       0.364613  0.000000e+00      0.0000       0.000000       0.000000  1.200000e+01
tax_liens                                   2260563.0       0.046771       0.377534  0.000000e+00      0.0000       0.000000       0.000000  8.500000e+01
tot_hi_cred_lim                             2190392.0  178242.753744  181574.814655  0.000000e+00  50731.0000  114298.500000  257755.000000  9.999999e+06
total_bal_ex_mort                           2210638.0   51022.938462   49911.235666  0.000000e+00  20892.0000   37864.000000   64350.000000  3.408095e+06
total_bc_limit                              2210638.0   23193.768173   23006.558239  0.000000e+00   8300.0000   16300.000000   30300.000000  1.569000e+06
total_il_high_credit_limit                  2190392.0   43732.013476   45072.982191  0.000000e+00  15000.0000   32696.000000   58804.250000  2.118996e+06
revol_bal_joint                              108020.0   33617.278847   28153.874309  0.000000e+00  15106.7500   26516.500000   43769.000000  1.110019e+06
sec_app_inq_last_6mths                       108021.0       0.633256       0.993401  0.000000e+00      0.0000       0.000000       1.000000  6.000000e+00
sec_app_mort_acc                             108021.0       1.538997       1.760569  0.000000e+00      0.0000       1.000000       2.000000  2.700000e+01
sec_app_open_acc                             108021.0      11.469455       6.627271  0.000000e+00      7.0000      10.000000      15.000000  8.200000e+01
sec_app_revol_util                           106184.0      58.169101      25.548212  0.000000e+00     39.8000      60.200000      78.600000  4.343000e+02
sec_app_open_act_il                          108021.0       3.010554       3.275893  0.000000e+00      1.0000       2.000000       4.000000  4.300000e+01
sec_app_num_rev_accts                        108021.0      12.533072       8.150964  0.000000e+00      7.0000      11.000000      17.000000  1.060000e+02
sec_app_chargeoff_within_12_mths             108021.0       0.046352       0.411496  0.000000e+00      0.0000       0.000000       0.000000  2.100000e+01
sec_app_collections_12_mths_ex_med           108021.0       0.077568       0.407996  0.000000e+00      0.0000       0.000000       0.000000  2.300000e+01
sec_app_mths_since_last_major_derog           35942.0      36.937928      23.924584  0.000000e+00     16.0000      36.000000      56.000000  1.850000e+02
deferral_term                                 10613.0       3.000000       0.000000  3.000000e+00      3.0000       3.000000       3.000000  3.000000e+00
hardship_amount                               10613.0     155.006696     129.113137  6.400000e-01     59.3700     119.040000     213.260000  9.439400e+02
hardship_length                               10613.0       3.000000       0.000000  3.000000e+00      3.0000       3.000000       3.000000  3.000000e+00
hardship_dpd                                  10613.0      13.686422       9.728138  0.000000e+00      5.0000      15.000000      22.000000  3.700000e+01
orig_projected_additional_accrued_interest     8426.0     454.840802     375.830737  1.920000e+00    174.9675     352.605000     622.792500  2.680890e+03
hardship_payoff_balance_amount                10613.0   11628.036442    7615.161123  5.573000e+01   5628.7300   10044.220000   16114.940000  4.030641e+04
hardship_last_payment_amount                  10613.0     193.606331     198.694368  1.000000e-02     43.7800     132.890000     284.180000  1.407860e+03
settlement_amount                             33056.0    5030.606922    3692.027842  4.421000e+01   2227.0000    4172.855000    6870.782500  3.360100e+04
settlement_percentage                         33056.0      47.775600       7.336379  2.000000e-01     45.0000      45.000000      50.000000  5.213500e+02
settlement_term                               33056.0      13.148596       8.192319  0.000000e+00      6.0000      14.000000      18.000000  1.810000e+02

In [3]:
pd.set_option('display.max_rows', 200)
pd.set_option('display.max_columns', 200)
pd.set_option('display.width', 1000)

In [21]:
appl_df.count(axis=0, numeric_only=False)

id                                                  0
member_id                                           0
loan_amnt                                     2260668
funded_amnt                                   2260668
funded_amnt_inv                               2260668
term                                          2260668
int_rate                                      2260668
installment                                   2260668
grade                                         2260668
sub_grade                                     2260668
emp_title                                     2093699
emp_length                                    2113761
home_ownership                                2260668
annual_inc                                    2260664
verification_status                           2260668
issue_d                                       2260668
loan_status                                   2260668
pymnt_plan                                    2260668
url                                                 0
desc                                           126067
purpose                                       2260668
title                                         2237343
zip_code                                      2260667
addr_state                                    2260668
dti                                           2258957
delinq_2yrs                                   2260639
earliest_cr_line                              2260639
inq_last_6mths                                2260638
mths_since_last_delinq                        1102166
mths_since_last_record                         359156
open_acc                                      2260639
pub_rec                                       2260639
revol_bal                                     2260668
revol_util                                    2258866
total_acc                                     2260639
initial_list_status                           2260668
out_prncp                                     2260668
out_prncp_inv                                 2260668
total_pymnt                                   2260668
total_pymnt_inv                               2260668
total_rec_prncp                               2260668
total_rec_int                                 2260668
total_rec_late_fee                            2260668
recoveries                                    2260668
collection_recovery_fee                       2260668
last_pymnt_d                                  2258242
last_pymnt_amnt                               2260668
next_pymnt_d                                   957061
last_credit_pull_d                            2260595
collections_12_mths_ex_med                    2260523
mths_since_last_major_derog                    580775
policy_code                                   2260668
application_type                              2260668
annual_inc_joint                               120710
dti_joint                                      120706
verification_status_joint                      115730
acc_now_delinq                                2260639
tot_coll_amt                                  2190392
tot_cur_bal                                   2190392
open_acc_6m                                   1394538
open_act_il                                   1394539
open_il_12m                                   1394539
open_il_24m                                   1394539
mths_since_rcnt_il                            1350744
total_bal_il                                  1394539
il_util                                       1191818
open_rv_12m                                   1394539
open_rv_24m                                   1394539
max_bal_bc                                    1394539
all_util                                      1394320
total_rev_hi_lim                              2190392
inq_fi                                        1394539
total_cu_tl                                   1394538
inq_last_12m                                  1394538
acc_open_past_24mths                          2210638
avg_cur_bal                                   2190322
bc_open_to_buy                                2185733
bc_util                                       2184597
chargeoff_within_12_mths                      2260523
delinq_amnt                                   2260639
mo_sin_old_il_acct                            2121597
mo_sin_old_rev_tl_op                          2190391
mo_sin_rcnt_rev_tl_op                         2190391
mo_sin_rcnt_tl                                2190392
mort_acc                                      2210638
mths_since_recent_bc                          2187256
mths_since_recent_bc_dlq                       519701
mths_since_recent_inq                         1965233
mths_since_recent_revol_delinq                 740359
num_accts_ever_120_pd                         2190392
num_actv_bc_tl                                2190392
num_actv_rev_tl                               2190392
num_bc_sats                                   2202078
num_bc_tl                                     2190392
num_il_tl                                     2190392
num_op_rev_tl                                 2190392
num_rev_accts                                 2190391
num_rev_tl_bal_gt_0                           2190392
num_sats                                      2202078
num_tl_120dpd_2m                              2107011
num_tl_30dpd                                  2190392
num_tl_90g_dpd_24m                            2190392
num_tl_op_past_12m                            2190392
pct_tl_nvr_dlq                                2190237
percent_bc_gt_75                              2185289
pub_rec_bankruptcies                          2259303
tax_liens                                     2260563
tot_hi_cred_lim                               2190392
total_bal_ex_mort                             2210638
total_bc_limit                                2210638
total_il_high_credit_limit                    2190392
revol_bal_joint                                108020
sec_app_earliest_cr_line                       108021
sec_app_inq_last_6mths                         108021
sec_app_mort_acc                               108021
sec_app_open_acc                               108021
sec_app_revol_util                             106184
sec_app_open_act_il                            108021
sec_app_num_rev_accts                          108021
sec_app_chargeoff_within_12_mths               108021
sec_app_collections_12_mths_ex_med             108021
sec_app_mths_since_last_major_derog             35942
hardship_flag                                 2260668
hardship_type                                   10613
hardship_reason                                 10613
hardship_status                                 10613
deferral_term                                   10613
hardship_amount                                 10613
hardship_start_date                             10613
hardship_end_date                               10613
payment_plan_start_date                         10613
hardship_length                                 10613
hardship_dpd                                    10613
hardship_loan_status                            10613
orig_projected_additional_accrued_interest       8426
hardship_payoff_balance_amount                  10613
hardship_last_payment_amount                    10613
disbursement_method                           2260668
debt_settlement_flag                          2260668
debt_settlement_flag_date                       33056
settlement_status                               33056
settlement_date                                 33056
settlement_amount                               33056
settlement_percentage                           33056
settlement_term                                 33056
dtype: int64

In [25]:
appl_df.count(axis=1, numeric_only=False)

0          103
1          104
2          102
3          102
4          102
5          102
6           96
7          102
8          106
9          103
10         105
11         102
12         102
13         104
14         101
15         118
16         104
17         113
18         106
19         102
20         106
21         102
22         104
23         120
24         102
25         112
26         102
27         101
28         103
29         102
30         101
31         106
32         106
33         106
34         112
35         104
36         101
37         102
38         102
39         117
40         102
41         102
42          96
43         100
44         101
45         105
46         100
47         102
48         100
49         102
50         103
51         106
52         106
53         102
54         104
55         101
56         105
57         115
58         102
59         105
60         116
61         100
62         102
63         102
64         103
65         105
66         102
67         114
68         102
69         105
70         102
71         103
72         103
73         102
74         102
75         103
76         104
77         101
78         102
79         104
80         103
81         104
82         117
83         101
84         102
85         103
86         103
87         105
88         102
89         102
90         115
91          99
92          99
93         106
94         102
95         106
96         101
97         104
98         102
99         105
          ...
2260568    116
2260569    104
2260570    108
2260571    102
2260572    101
2260573    119
2260574    102
2260575    105
2260576    103
2260577    101
2260578    112
2260579    115
2260580    103
2260581    102
2260582    101
2260583    101
2260584    104
2260585    105
2260586    103
2260587    102
2260588    103
2260589    102
2260590    103
2260591    100
2260592    104
2260593    105
2260594    101
2260595    102
2260596    104
2260597    103
2260598    102
2260599     97
2260600    106
2260601    101
2260602    103
2260603    104
2260604    120
2260605    105
2260606    104
2260607    101
2260608    102
2260609    103
2260610    104
2260611    100
2260612    103
2260613    112
2260614    102
2260615    115
2260616    104
2260617    115
2260618    119
2260619    103
2260620    100
2260621    104
2260622    105
2260623    104
2260624    101
2260625    102
2260626    102
2260627    102
2260628    102
2260629    106
2260630     99
2260631    105
2260632    104
2260633    106
2260634    101
2260635    102
2260636    104
2260637    106
2260638    103
2260639    104
2260640    103
2260641    104
2260642    103
2260643    104
2260644    102
2260645    103
2260646    119
2260647    104
2260648    114
2260649    118
2260650    101
2260651    115
2260652    103
2260653    103
2260654    104
2260655    104
2260656    102
2260657    116
2260658    105
2260659    104
2260660    102
2260661    104
2260662    102
2260663    102
2260664    119
2260665    102
2260666    103
2260667     99
Length: 2260668, dtype: int64

In [4]:
appl_df.settlement_status.value_counts()

ACTIVE      14811
COMPLETE    13517
BROKEN       4728
Name: settlement_status, dtype: int64

In [5]:
appl_df.drop('member_id', axis=1, inplace=True)
appl_df.drop('id', axis=1, inplace=True)

In [6]:
appl_df.loan_status.value_counts()

Fully Paid                                             1041952
Current                                                 919695
Charged Off                                             261655
Late (31-120 days)                                       21897
In Grace Period                                           8952
Late (16-30 days)                                         3737
Does not meet the credit policy. Status:Fully Paid        1988
Does not meet the credit policy. Status:Charged Off        761
Default                                                     31
Name: loan_status, dtype: int64

In [8]:
appl_df.shape

(2260668, 143)

In [32]:
appl_df.isnull().sum().value_counts()

0          32
70276      16
2250055    13
2152647     8
866129      8
29          7
2227612     6
50030       4
866130      3
2260668     3
70277       3
58590       2
145         2
1068850     1
139071      1
2139962     1
166969      1
1303607     1
2139958     1
1802        1
1           1
295435      1
4           1
76071       1
2152648     1
70431       1
30          1
23325       1
1679893     1
866348      1
2154484     1
2134601     1
1365        1
146907      1
153657      1
2252242     1
70346       1
1901512     1
73412       1
74935       1
1520309     1
1711        1
2144938     1
1740967     1
73          1
2426        1
75379       1
105         1
1158502     1
2224726     1
909924      1
dtype: int64

In [9]:
df_cleanAppl = appl_df[(appl_df.loan_status == 'Fully Paid') | (appl_df.loan_status == 'Charged Off')]

In [10]:
df_cleanAppl.loan_status.value_counts()

Fully Paid     1041952
Charged Off     261655
Name: loan_status, dtype: int64

In [11]:
df_cleanAppl.shape

(1303607, 143)

In [55]:
df_cleanAppl.loan_status.value_counts(normalize=True) #About 80% are ‘Fully Paid’ and 20% are ‘Charged Off’So our sample is biased in this case

Fully Paid     0.799284
Charged Off    0.200716
Name: loan_status, dtype: float64

In [12]:
df_cleanAppl.isnull().any().value_counts() #103 COLUMNS HAVE MISSING VALUES

True     103
False     40
dtype: int64

In [13]:
total_num = df_cleanAppl.isnull().sum().sort_values(ascending=False)
perc = df_cleanAppl.isnull().sum()/df_cleanAppl.isnull().count() *100
perc1 = (round(perc,2).sort_values(ascending=False))

# Creating a data frame:
df_miss = pd.concat([total_num, perc1], axis=1, keys =["Total Missing Values", "Percentage %"], sort=True).sort_values(by =["Percentage %"], ascending = False)
df_miss.reset_index(inplace=True)

In [88]:
df_miss

                                            Total Missing Values  Percentage %
url                                                      1303607        100.00
next_pymnt_d                                             1303607        100.00
orig_projected_additional_accrued_interest               1300174         99.74
deferral_term                                            1298272         99.59
hardship_last_payment_amount                             1298272         99.59
hardship_payoff_balance_amount                           1298272         99.59
hardship_end_date                                        1298272         99.59
hardship_dpd                                             1298272         99.59
hardship_amount                                          1298272         99.59
hardship_reason                                          1298272         99.59
hardship_start_date                                      1298272         99.59
hardship_status                                          1298272         99.59
hardship_type                                            1298272         99.59
hardship_loan_status                                     1298272         99.59
hardship_length                                          1298272         99.59
payment_plan_start_date                                  1298272         99.59
sec_app_mths_since_last_major_derog                      1297675         99.54
sec_app_revol_util                                       1287389         98.76
sec_app_num_rev_accts                                    1287096         98.73
sec_app_chargeoff_within_12_mths                         1287096         98.73
revol_bal_joint                                          1287097         98.73
sec_app_inq_last_6mths                                   1287096         98.73
sec_app_mort_acc                                         1287096         98.73
sec_app_open_acc                                         1287096         98.73
sec_app_earliest_cr_line                                 1287096         98.73
sec_app_open_act_il                                      1287096         98.73
sec_app_collections_12_mths_ex_med                       1287096         98.73
verification_status_joint                                1280516         98.23
dti_joint                                                1280372         98.22
annual_inc_joint                                         1280370         98.22
settlement_amount                                        1271618         97.55
settlement_term                                          1271618         97.55
settlement_status                                        1271618         97.55
settlement_date                                          1271618         97.55
settlement_percentage                                    1271618         97.55
debt_settlement_flag_date                                1271618         97.55
desc                                                     1180280         90.54
mths_since_last_record                                   1081841         82.99
mths_since_recent_bc_dlq                                  994461         76.29
mths_since_last_major_derog                               961240         73.74
il_util                                                   870939         66.81
mths_since_recent_revol_delinq                            867772         66.57
mths_since_rcnt_il                                        817059         62.68
total_cu_tl                                               804063         61.68
open_il_12m                                               804062         61.68
open_act_il                                               804062         61.68
open_acc_6m                                               804063         61.68
open_rv_24m                                               804062         61.68
open_rv_12m                                               804062         61.68
max_bal_bc                                                804062         61.68
open_il_24m                                               804062         61.68
inq_last_12m                                              804063         61.68
total_bal_il                                              804062         61.68
all_util                                                  804113         61.68
inq_fi                                                    804062         61.68
mths_since_last_delinq                                    657824         50.46
mths_since_recent_inq                                     169549         13.01
num_tl_120dpd_2m                                          115570          8.87
mo_sin_old_il_acct                                        104295          8.00
emp_title                                                  82579          6.33
emp_length                                                 75454          5.79
pct_tl_nvr_dlq                                             67681          5.19
num_accts_ever_120_pd                                      67527          5.18
num_op_rev_tl                                              67527          5.18
num_rev_accts                                              67528          5.18
num_tl_90g_dpd_24m                                         67527          5.18
num_rev_tl_bal_gt_0                                        67527          5.18
num_tl_30dpd                                               67527          5.18
num_bc_tl                                                  67527          5.18
num_tl_op_past_12m                                         67527          5.18
tot_hi_cred_lim                                            67527          5.18
num_il_tl                                                  67527          5.18
num_actv_rev_tl                                            67527          5.18
tot_cur_bal                                                67527          5.18
num_actv_bc_tl                                             67527          5.18
total_il_high_credit_limit                                 67527          5.18
tot_coll_amt                                               67527          5.18
avg_cur_bal                                                67548          5.18
mo_sin_rcnt_tl                                             67527          5.18
mo_sin_rcnt_rev_tl_op                                      67528          5.18
mo_sin_old_rev_tl_op                                       67528          5.18
total_rev_hi_lim                                           67527          5.18
bc_util                                                    61386          4.71
percent_bc_gt_75                                           61047          4.68
bc_open_to_buy                                             60639          4.65
mths_since_recent_bc                                       59741          4.58
num_bc_sats                                                55841          4.28
num_sats                                                   55841          4.28
acc_open_past_24mths                                       47281          3.63
total_bal_ex_mort                                          47281          3.63
total_bc_limit                                             47281          3.63
mort_acc                                                   47281          3.63
title                                                      15426          1.18
last_pymnt_d                                                2260          0.17
revol_util                                                   810          0.06
pub_rec_bankruptcies                                         697          0.05
dti                                                          312          0.02
total_rec_late_fee                                             0          0.00
total_rec_prncp                                                0          0.00
total_pymnt                                                    0          0.00
sub_grade                                                      0          0.00
tax_liens                                                     39          0.00
term                                                           0          0.00
verification_status                                            0          0.00
total_rec_int                                                  0          0.00
total_pymnt_inv                                                0          0.00
total_acc                                                      0          0.00
acc_now_delinq                                                 0          0.00
revol_bal                                                      0          0.00
delinq_2yrs                                                    0          0.00
grade                                                          0          0.00
funded_amnt_inv                                                0          0.00
funded_amnt                                                    0          0.00
earliest_cr_line                                               0          0.00
disbursement_method                                            0          0.00
delinq_amnt                                                    0          0.00
debt_settlement_flag                                           0          0.00
home_ownership                                                 0          0.00
collections_12_mths_ex_med                                    56          0.00
collection_recovery_fee                                        0          0.00
chargeoff_within_12_mths                                      56          0.00
application_type                                               0          0.00
annual_inc                                                     0          0.00
addr_state                                                     0          0.00
hardship_flag                                                  0          0.00
initial_list_status                                            0          0.00
recoveries                                                     0          0.00
open_acc                                                       0          0.00
pymnt_plan                                                     0          0.00
purpose                                                        0          0.00
pub_rec                                                        0          0.00
policy_code                                                    0          0.00
out_prncp_inv                                                  0          0.00
out_prncp                                                      0          0.00
loan_status                                                    0          0.00
inq_last_6mths                                                 1          0.00
loan_amnt                                                      0          0.00
last_pymnt_amnt                                                0          0.00
last_credit_pull_d                                            54          0.00
issue_d                                                        0          0.00
int_rate                                                       0          0.00
installment                                                    0          0.00
zip_code                                                       1          0.00

In [68]:
perc1

url                                           100.00
next_pymnt_d                                  100.00
orig_projected_additional_accrued_interest     99.74
hardship_end_date                              99.59
hardship_length                                99.59
hardship_type                                  99.59
hardship_reason                                99.59
hardship_status                                99.59
deferral_term                                  99.59
hardship_amount                                99.59
hardship_start_date                            99.59
payment_plan_start_date                        99.59
hardship_loan_status                           99.59
hardship_dpd                                   99.59
hardship_payoff_balance_amount                 99.59
hardship_last_payment_amount                   99.59
sec_app_mths_since_last_major_derog            99.54
sec_app_revol_util                             98.76
sec_app_chargeoff_within_12_mths               98.73
sec_app_num_rev_accts                          98.73
sec_app_earliest_cr_line                       98.73
sec_app_open_acc                               98.73
sec_app_collections_12_mths_ex_med             98.73
sec_app_open_act_il                            98.73
revol_bal_joint                                98.73
sec_app_inq_last_6mths                         98.73
sec_app_mort_acc                               98.73
verification_status_joint                      98.23
annual_inc_joint                               98.22
dti_joint                                      98.22
settlement_percentage                          97.55
settlement_term                                97.55
debt_settlement_flag_date                      97.55
settlement_status                              97.55
settlement_date                                97.55
settlement_amount                              97.55
desc                                           90.54
mths_since_last_record                         82.99
mths_since_recent_bc_dlq                       76.29
mths_since_last_major_derog                    73.74
il_util                                        66.81
mths_since_recent_revol_delinq                 66.57
mths_since_rcnt_il                             62.68
open_il_24m                                    61.68
open_il_12m                                    61.68
total_bal_il                                   61.68
open_act_il                                    61.68
open_rv_12m                                    61.68
open_rv_24m                                    61.68
max_bal_bc                                     61.68
all_util                                       61.68
inq_fi                                         61.68
total_cu_tl                                    61.68
open_acc_6m                                    61.68
inq_last_12m                                   61.68
mths_since_last_delinq                         50.46
mths_since_recent_inq                          13.01
num_tl_120dpd_2m                                8.87
mo_sin_old_il_acct                              8.00
emp_title                                       6.33
emp_length                                      5.79
pct_tl_nvr_dlq                                  5.19
num_rev_tl_bal_gt_0                             5.18
num_tl_30dpd                                    5.18
num_tl_90g_dpd_24m                              5.18
num_tl_op_past_12m                              5.18
num_accts_ever_120_pd                           5.18
num_op_rev_tl                                   5.18
tot_cur_bal                                     5.18
tot_coll_amt                                    5.18
num_actv_bc_tl                                  5.18
tot_hi_cred_lim                                 5.18
num_rev_accts                                   5.18
total_rev_hi_lim                                5.18
mo_sin_old_rev_tl_op                            5.18
avg_cur_bal                                     5.18
num_actv_rev_tl                                 5.18
mo_sin_rcnt_tl                                  5.18
mo_sin_rcnt_rev_tl_op                           5.18
num_il_tl                                       5.18
total_il_high_credit_limit                      5.18
num_bc_tl                                       5.18
bc_util                                         4.71
percent_bc_gt_75                                4.68
bc_open_to_buy                                  4.65
mths_since_recent_bc                            4.58
num_sats                                        4.28
num_bc_sats                                     4.28
acc_open_past_24mths                            3.63
mort_acc                                        3.63
total_bal_ex_mort                               3.63
total_bc_limit                                  3.63
title                                           1.18
last_pymnt_d                                    0.17
revol_util                                      0.06
pub_rec_bankruptcies                            0.05
dti                                             0.02
verification_status                             0.00
addr_state                                      0.00
zip_code                                        0.00
purpose                                         0.00
disbursement_method                             0.00
debt_settlement_flag                            0.00
pymnt_plan                                      0.00
loan_status                                     0.00
issue_d                                         0.00
policy_code                                     0.00
delinq_2yrs                                     0.00
home_ownership                                  0.00
chargeoff_within_12_mths                        0.00
delinq_amnt                                     0.00
sub_grade                                       0.00
grade                                           0.00
installment                                     0.00
int_rate                                        0.00
term                                            0.00
funded_amnt_inv                                 0.00
funded_amnt                                     0.00
annual_inc                                      0.00
earliest_cr_line                                0.00
collections_12_mths_ex_med                      0.00
total_pymnt_inv                                 0.00
last_credit_pull_d                              0.00
application_type                                0.00
last_pymnt_amnt                                 0.00
tax_liens                                       0.00
collection_recovery_fee                         0.00
recoveries                                      0.00
total_rec_late_fee                              0.00
total_rec_int                                   0.00
total_rec_prncp                                 0.00
total_pymnt                                     0.00
inq_last_6mths                                  0.00
out_prncp_inv                                   0.00
out_prncp                                       0.00
initial_list_status                             0.00
total_acc                                       0.00
revol_bal                                       0.00
pub_rec                                         0.00
open_acc                                        0.00
hardship_flag                                   0.00
acc_now_delinq                                  0.00
loan_amnt                                       0.00
dtype: float64

In [69]:
total_num

url                                           1303607
next_pymnt_d                                  1303607
orig_projected_additional_accrued_interest    1300174
hardship_end_date                             1298272
hardship_start_date                           1298272
hardship_type                                 1298272
hardship_reason                               1298272
hardship_status                               1298272
deferral_term                                 1298272
hardship_last_payment_amount                  1298272
hardship_payoff_balance_amount                1298272
hardship_loan_status                          1298272
hardship_dpd                                  1298272
hardship_length                               1298272
payment_plan_start_date                       1298272
hardship_amount                               1298272
sec_app_mths_since_last_major_derog           1297675
sec_app_revol_util                            1287389
revol_bal_joint                               1287097
sec_app_inq_last_6mths                        1287096
sec_app_earliest_cr_line                      1287096
sec_app_collections_12_mths_ex_med            1287096
sec_app_chargeoff_within_12_mths              1287096
sec_app_num_rev_accts                         1287096
sec_app_open_act_il                           1287096
sec_app_open_acc                              1287096
sec_app_mort_acc                              1287096
verification_status_joint                     1280516
dti_joint                                     1280372
annual_inc_joint                              1280370
settlement_percentage                         1271618
settlement_term                               1271618
debt_settlement_flag_date                     1271618
settlement_status                             1271618
settlement_date                               1271618
settlement_amount                             1271618
desc                                          1180280
mths_since_last_record                        1081841
mths_since_recent_bc_dlq                       994461
mths_since_last_major_derog                    961240
il_util                                        870939
mths_since_recent_revol_delinq                 867772
mths_since_rcnt_il                             817059
all_util                                       804113
open_acc_6m                                    804063
total_cu_tl                                    804063
inq_last_12m                                   804063
total_bal_il                                   804062
open_il_24m                                    804062
open_rv_12m                                    804062
inq_fi                                         804062
open_rv_24m                                    804062
max_bal_bc                                     804062
open_act_il                                    804062
open_il_12m                                    804062
mths_since_last_delinq                         657824
mths_since_recent_inq                          169549
num_tl_120dpd_2m                               115570
mo_sin_old_il_acct                             104295
emp_title                                       82579
emp_length                                      75454
pct_tl_nvr_dlq                                  67681
avg_cur_bal                                     67548
num_rev_accts                                   67528
mo_sin_rcnt_rev_tl_op                           67528
mo_sin_old_rev_tl_op                            67528
num_tl_op_past_12m                              67527
num_rev_tl_bal_gt_0                             67527
tot_cur_bal                                     67527
tot_coll_amt                                    67527
tot_hi_cred_lim                                 67527
total_rev_hi_lim                                67527
num_tl_90g_dpd_24m                              67527
total_il_high_credit_limit                      67527
num_actv_bc_tl                                  67527
num_bc_tl                                       67527
num_op_rev_tl                                   67527
num_actv_rev_tl                                 67527
num_tl_30dpd                                    67527
num_accts_ever_120_pd                           67527
mo_sin_rcnt_tl                                  67527
num_il_tl                                       67527
bc_util                                         61386
percent_bc_gt_75                                61047
bc_open_to_buy                                  60639
mths_since_recent_bc                            59741
num_sats                                        55841
num_bc_sats                                     55841
total_bc_limit                                  47281
mort_acc                                        47281
acc_open_past_24mths                            47281
total_bal_ex_mort                               47281
title                                           15426
last_pymnt_d                                     2260
revol_util                                        810
pub_rec_bankruptcies                              697
dti                                               312
collections_12_mths_ex_med                         56
chargeoff_within_12_mths                           56
last_credit_pull_d                                 54
tax_liens                                          39
inq_last_6mths                                      1
zip_code                                            1
funded_amnt_inv                                     0
issue_d                                             0
acc_now_delinq                                      0
purpose                                             0
disbursement_method                                 0
debt_settlement_flag                                0
pymnt_plan                                          0
loan_status                                         0
verification_status                                 0
term                                                0
annual_inc                                          0
funded_amnt                                         0
delinq_amnt                                         0
sub_grade                                           0
grade                                               0
installment                                         0
int_rate                                            0
home_ownership                                      0
last_pymnt_amnt                                     0
addr_state                                          0
out_prncp                                           0
collection_recovery_fee                             0
recoveries                                          0
total_rec_late_fee                                  0
total_rec_int                                       0
total_rec_prncp                                     0
total_pymnt_inv                                     0
total_pymnt                                         0
out_prncp_inv                                       0
initial_list_status                                 0
delinq_2yrs                                         0
total_acc                                           0
policy_code                                         0
revol_bal                                           0
pub_rec                                             0
open_acc                                            0
hardship_flag                                       0
application_type                                    0
earliest_cr_line                                    0
loan_amnt                                           0
dtype: int64

In [14]:
df_miss[df_miss['Percentage %']>50].count()

index                   56
Total Missing Values    56
Percentage %            56
dtype: int64

In [77]:
perc1.shape

(143,)

In [92]:
df_miss.count()

Total Missing Values    143
Percentage %            143
dtype: int64

In [15]:
df_NewAppl = df_cleanAppl.drop(df_miss[df_miss["Percentage %"]>50]["index"], axis = 1)

In [17]:
df_NewAppl.shape

(1303607, 87)

In [101]:
df_miss[df_miss["Percentage %"]>50]["index"] # features that were dropped

0                                            url
1                                   next_pymnt_d
2     orig_projected_additional_accrued_interest
3                                  deferral_term
4                   hardship_last_payment_amount
5                 hardship_payoff_balance_amount
6                              hardship_end_date
7                                   hardship_dpd
8                                hardship_amount
9                                hardship_reason
10                           hardship_start_date
11                               hardship_status
12                                 hardship_type
13                          hardship_loan_status
14                               hardship_length
15                       payment_plan_start_date
16           sec_app_mths_since_last_major_derog
17                            sec_app_revol_util
18                         sec_app_num_rev_accts
19              sec_app_chargeoff_within_12_mths
20                               revol_bal_joint
21                        sec_app_inq_last_6mths
22                              sec_app_mort_acc
23                              sec_app_open_acc
24                      sec_app_earliest_cr_line
25                           sec_app_open_act_il
26            sec_app_collections_12_mths_ex_med
27                     verification_status_joint
28                                     dti_joint
29                              annual_inc_joint
30                             settlement_amount
31                               settlement_term
32                             settlement_status
33                               settlement_date
34                         settlement_percentage
35                     debt_settlement_flag_date
36                                          desc
37                        mths_since_last_record
38                      mths_since_recent_bc_dlq
39                   mths_since_last_major_derog
40                                       il_util
41                mths_since_recent_revol_delinq
42                            mths_since_rcnt_il
43                                   total_cu_tl
44                                   open_il_12m
45                                   open_act_il
46                                   open_acc_6m
47                                   open_rv_24m
48                                   open_rv_12m
49                                    max_bal_bc
50                                   open_il_24m
51                                  inq_last_12m
52                                  total_bal_il
53                                      all_util
54                                        inq_fi
55                        mths_since_last_delinq
Name: index, dtype: object

In [20]:
keep_list = ['addr_state', 'annual_inc', 'application_type', 'dti', 'earliest_cr_line', 'emp_length', 'emp_title', 'fico_range_high', 'fico_range_low', 'grade', 'home_ownership', 'id', 'initial_list_status', 'installment', 'int_rate', 'issue_d', 'loan_amnt', 'loan_status', 'mort_acc', 'open_acc', 'pub_rec', 'pub_rec_bankruptcies', 'purpose', 'revol_bal', 'revol_util', 'sub_grade', 'term', 'title', 'total_acc', 'verification_status', 'zip_code']
drop_list = [col for col in df_NewAppl.columns if col not in keep_list]
print(drop_list)

['funded_amnt', 'funded_amnt_inv', 'pymnt_plan', 'delinq_2yrs', 'inq_last_6mths', 'out_prncp', 'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int', 'total_rec_late_fee', 'recoveries', 'collection_recovery_fee', 'last_pymnt_d', 'last_pymnt_amnt', 'last_credit_pull_d', 'collections_12_mths_ex_med', 'policy_code', 'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'total_rev_hi_lim', 'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util', 'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct', 'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl', 'mths_since_recent_bc', 'mths_since_recent_inq', 'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl', 'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl', 'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_120dpd_2m', 'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m', 'pct_tl_nvr_dlq', 'percent_bc_gt_75', 'tax_liens', 'tot_hi_cred_lim', 'total_bal_ex_mort', 'total_bc_limit', 'total_il_high_credit_limit', 'hardship_flag', 'disbursement_method', 'debt_settlement_flag']

In [21]:
df_NewAppl.drop(labels=drop_list, axis=1, inplace=True)

In [22]:
df_NewAppl.shape

(1303607, 28)

In [25]:
sorted(df_NewAppl.columns)

['addr_state',
 'annual_inc',
 'application_type',
 'dti',
 'earliest_cr_line',
 'emp_length',
 'emp_title',
 'grade',
 'home_ownership',
 'initial_list_status',
 'installment',
 'int_rate',
 'issue_d',
 'loan_amnt',
 'loan_status',
 'mort_acc',
 'open_acc',
 'pub_rec',
 'pub_rec_bankruptcies',
 'purpose',
 'revol_bal',
 'revol_util',
 'sub_grade',
 'term',
 'title',
 'total_acc',
 'verification_status',
 'zip_code']

In [28]:
#Zip code is in the format-891xx    900xx    etc. We have clean that.
df_NewAppl.zip_code = df_NewAppl.zip_code.str.replace("xx","")

In [29]:
#Next is formatting the dates- for e.g. Oct-2013 to 2015-10-01  format
df_NewAppl.issue_d = pd.to_datetime(df_NewAppl.issue_d,infer_datetime_format=True)
df_NewAppl['earliest_cr_line'] = pd.to_datetime(df_NewAppl['earliest_cr_line'],infer_datetime_format=True)

Next is cleaning up the employment length feature as follows-
The values are -
10+ years
 < 1 year
 2 years
 3 years etc
We will make it as 0/1/2/3/...10 etc

In [32]:
df_NewAppl['emp_length'].replace(to_replace='10+ years', value='10 years', inplace=True)
df_NewAppl['emp_length'].replace('< 1 year', '0 years', inplace=True)

def emp_length_to_int(str_val):
    if pd.isnull(str_val):
        return str_val
    else:
        return np.int8(str_val.split()[0])
df_NewAppl['emp_length'] = df_NewAppl['emp_length'].apply(emp_length_to_int)

In [ ]:
#Next we will move on to EDA with individual features